### ISSUE TITLE
Can't seem to switch from web3 modal wagmi config to privy wagmi config 

### ISSUE THREAD

**Issue by dipanshuhappy** [VoiceDeck/app#110]
When i do switch i get this error

```
Failed to set fetch cache URL {
  href: 'https://api.hypercerts.org/v1/graphql',
  origin: 'https://api.hypercerts.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'api.hypercerts.org',
  hostname: 'api.hypercerts.org',
  port: '',
  pathname: '/v1/graphql',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
} Error: fetch for over 2MB of data can not be cached
    at IncrementalCache.set (/Users/dipanshu/Desktop/projects/voicedeck/app/node_modules/next/dist/server/lib/incremental-cache/index.js:387:23)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/patch-fetch.js:427:74)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/patch-fetch.js:216:16)
    at async eval (webpack-internal:///(rsc)/./node_modules/graphql-request/build/legacy/helpers/runRequest.js:132:12)
    at async runRequest (webpack-internal:///(rsc)/./node_modules/graphql-request/build/legacy/helpers/runRequest.js:33:27)
    at async GraphQLClient.request (webpack-internal:///(rsc)/./node_modules/graphql-request/build/legacy/classes/GraphQLClient.js:76:26)
    at async getHypercertsByOwner (webpack-internal:///(rsc)/./hypercerts/getHypercertsByOwner.ts:33:26)
    at async fetchReports (webpack-internal:///(rsc)/./lib/impact-reports.ts:46:35)
    at async ReportsPage (webpack-internal:///(rsc)/./app/reports/page.tsx:30:25)
[Directus] Fetching CMS contents from remote
[Directus] fetched CMS contents:  27
[server] Processing claim with ID: 10-0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07-18667890649282684105600730963706804080476160.
[server] Processing claim with ID: 10-0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07-18666869802181921290210340839884508775841792.
[server] Processing claim with ID: 10-0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07-18669251778750367859454584462136531153321984.
[server] Processing claim with ID: 10-0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07-18669592061117288797918047836743962921533440.
[server] Failed to fetch reports: Error: [server] CMS content for report titled 'Women Allowed to Work in Government Program' not found.
Failed to fetch reports: Error: [server] Failed to fetch reports: Error: [server] CMS content for report titled 'Women Allowed to Work in Government Program' not found.
    at fetchReports (webpack-internal:///(rsc)/./lib/impact-reports.ts:75:15)
    at async ReportsPage (webpack-internal:///(rsc)/./app/reports/page.tsx:30:25)
 ⨯ app/reports/page.tsx (29:8) @ ReportsPage
 ⨯ Error: Failed to fetch reports
    at ReportsPage (./app/reports/page.tsx:41:15)
  27 |  } catch (error) {
  28 |          console.error("Failed to fetch reports:", error);
> 29 |          throw new Error("Failed to fetch reports");
     |               ^
  30 |  }
  31 |
  32 |  return (
 ⨯ app/reports/page.tsx (29:8) @ ReportsPage
 ⨯ Error: Failed to fetch reports
    at ReportsPage (./app/reports/page.tsx:41:15)
digest: "4003365011"
  27 |  } catch (error) {
  28 |          console.error("Failed to fetch reports:", error);
> 29 |          throw new Error("Failed to fetch reports");
     |               ^
  30 |  }
  31 |
  32 |  return (
 ○ Compiling /not-found ...
 ✓ Compiled /not-found in 2.9s (9441 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
[server] Fetching reports from remote using owner address: 0xd8813c65a4a21772c360f32b2c7960040fa84a8b
Failed to set fetch cache URL {
  href: 'https://api.hypercerts.org/v1/graphql',
  origin: 'https://api.hypercerts.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'api.hypercerts.org',
  hostname: 'api.hypercerts.org',
  port: '',
  pathname: '/v1/graphql',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
} Error: fetch for over 2MB of data can not be cached
    at IncrementalCache.set (/Users/dipanshu/Desktop/projects/voicedeck/app/node_modules/next/dist/server/lib/incremental-cache/index.js:387:23)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/patch-fetch.js:427:74)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/patch-fetch.js:216:16)
    at async eval (webpack-internal:///(rsc)/./node_modules/graphql-request/build/legacy/helpers/runRequest.js:132:12)
    at async runRequest (webpack-internal:///(rsc)/./node_modules/graphql-request/build/legacy/helpers/runRequest.js:33:27)
    at async GraphQLClient.request (webpack-internal:///(rsc)/./node_modules/graphql-request/build/legacy/classes/GraphQLClient.js:76:26)
    at async getHypercertsByOwner (webpack-internal:///(rsc)/./hypercerts/getHypercertsByOwner.ts:33:26)
    at async fetchReports (webpack-internal:///(rsc)/./lib/impact-reports.ts:46:35)
    at async ReportsPage (webpack-internal:///(rsc)/./app/reports/page.tsx:30:25)
[Directus] Fetching CMS contents from remote
[Directus] fetched CMS contents:  27
[server] Processing claim with ID: 10-0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07-18667890649282684105600730963706804080476160.
[server] Processing claim with ID: 10-0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07-18666869802181921290210340839884508775841792.
[server] Processing claim with ID: 10-0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07-18669251778750367859454584462136531153321984.
[server] Processing claim with ID: 10-0x822F17A9A5EeCFd66dBAFf7946a8071C265D1d07-18669592061117288797918047836743962921533440.
[server] Failed to fetch reports: Error: [server] CMS content for report titled 'Women Allowed to Work in Government Program' not found.
Failed to fetch reports: Error: [server] Failed to fetch reports: Error: [server] CMS content for report titled 'Women Allowed to Work in Government Program' not found.
    at fetchReports (webpack-internal:///(rsc)/./lib/impact-reports.ts:75:15)
    at async ReportsPage (webpack-internal:///(rsc)/./app/reports/page.tsx:30:25)
 ⨯ app/reports/page.tsx (29:8) @ ReportsPage
 ⨯ Error: Failed to fetch reports
    at ReportsPage (./app/reports/page.tsx:41:15)
  27 |  } catch (error) {
  28 |          console.error("Failed to fetch reports:", error);
> 29 |          throw new Error("Failed to fetch reports");
     |               ^
  30 |  }
  31 |
  32 |  return (
 ⨯ app/reports/page.tsx (29:8) @ ReportsPage
 ⨯ Error: Failed to fetch reports
    at ReportsPage (./app/reports/page.tsx:41:15)
digest: "4003365011"
  27 |  } catch (error) {
  28 |          console.error("Failed to fetch reports:", error);
> 29 |          throw new Error("Failed to fetch reports");
     |               ^
  30 |  }
  31 |
  
  ```

**Comment by dipanshuhappy** [comment]
Here is a branch to recreate this error 
https://github.com/VoiceDeck/app/tree/issue/privy-wagmi
